
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '560DF84AF19A5F3BC4AF726F2A1FD560'
    
_lr_action_items = {'ORDINAL':([0,2,],[1,7,]),'ON':([0,],[2,]),'DAY':([0,7,],[5,8,]),'$end':([0,1,2,3,4,5,6,8,],[-7,-3,-1,-4,0,-2,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[4,]),'day':([0,],[3,]),'empty':([0,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> ON','start',1,'p_start','PLY12days.py',57),
  ('start -> DAY','start',1,'p_start','PLY12days.py',58),
  ('start -> ORDINAL','start',1,'p_start','PLY12days.py',59),
  ('start -> day','start',1,'p_start','PLY12days.py',60),
  ('start -> empty','start',1,'p_start','PLY12days.py',61),
  ('day -> ON ORDINAL DAY','day',3,'p_day','PLY12days.py',66),
  ('empty -> <empty>','empty',0,'p_empty','PLY12days.py',70),
]
